import { User, Location, Product, Document, StockLedgerEntry, StockLevel } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-001',
    name: 'Sarah Connor',
    email: 'sarah.connor@stocksense.io',
    role: 'MANAGER',
    created_at: '2026-01-15T08:00:00Z',
  },
  {
    id: 'usr-002',
    name: 'John Doe',
    email: 'john.doe@stocksense.io',
    role: 'STAFF',
    created_at: '2026-02-01T09:30:00Z',
  },
];

export const INITIAL_LOCATIONS: Location[] = [
  {
    id: 'loc-001',
    name: 'Main Warehouse',
    code: 'WH-01',
    type: 'WAREHOUSE',
    description: 'Central receiving and bulk storage facility',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'loc-002',
    name: 'Production Floor',
    code: 'LOC-PROD',
    type: 'PRODUCTION',
    description: 'Active assembly and manufacturing line staging',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'loc-003',
    name: 'Rack A-101',
    code: 'RCK-A101',
    type: 'RACK',
    description: 'High-density shelving for small components & fasteners',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'loc-004',
    name: 'Rack B-202',
    code: 'RCK-B202',
    type: 'RACK',
    description: 'Heavy raw materials and metal bar storage',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'loc-005',
    name: 'Cold Storage Vault',
    code: 'WH-COLD',
    type: 'WAREHOUSE',
    description: 'Climate-controlled storage for lubricants & polymers',
    created_at: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    name: 'Structural Steel Rod (12mm)',
    sku: 'STL-ROD-012',
    category: 'Raw Materials',
    unit_of_measure: 'kg',
    min_reorder_level: 250,
    created_at: '2026-01-10T10:00:00Z',
  },
  {
    id: 'prod-002',
    name: 'Aluminum Alloy Sheet (3mm)',
    sku: 'ALU-SHT-003',
    category: 'Raw Materials',
    unit_of_measure: 'pcs',
    min_reorder_level: 50,
    created_at: '2026-01-10T10:15:00Z',
  },
  {
    id: 'prod-003',
    name: 'Hex Flange Bolts M8x30',
    sku: 'FST-BLT-M830',
    category: 'Fasteners',
    unit_of_measure: 'pcs',
    min_reorder_level: 1000,
    created_at: '2026-01-11T11:00:00Z',
  },
  {
    id: 'prod-004',
    name: 'Nylon Lock Nuts M8',
    sku: 'FST-NUT-M800',
    category: 'Fasteners',
    unit_of_measure: 'pcs',
    min_reorder_level: 800,
    created_at: '2026-01-11T11:30:00Z',
  },
  {
    id: 'prod-005',
    name: 'Synthetic Industrial Gear Oil ISO 320',
    sku: 'LUB-OIL-320',
    category: 'Fluids & Chemicals',
    unit_of_measure: 'liters',
    min_reorder_level: 150,
    created_at: '2026-01-12T14:00:00Z',
  },
  {
    id: 'prod-006',
    name: 'Precision Ball Bearing 6205-2RS',
    sku: 'BRG-6205-RS',
    category: 'Mechanical',
    unit_of_measure: 'pcs',
    min_reorder_level: 40,
    created_at: '2026-01-15T09:00:00Z',
  },
  {
    id: 'prod-007',
    name: 'Heavy Duty Nitrile Gloves (L)',
    sku: 'PPE-GLV-00L',
    category: 'Safety & PPE',
    unit_of_measure: 'boxes',
    min_reorder_level: 30,
    created_at: '2026-01-18T13:00:00Z',
  },
  {
    id: 'prod-008',
    name: 'Corrugated Shipping Box 400x300x300',
    sku: 'PKG-BOX-403',
    category: 'Packaging',
    unit_of_measure: 'pcs',
    min_reorder_level: 200,
    created_at: '2026-01-20T16:00:00Z',
  },
];

export const INITIAL_STOCK_LEVELS: StockLevel[] = [
  // Steel Rod: 500 in Main WH, 120 on Prod Floor
  { product_id: 'prod-001', location_id: 'loc-001', current_quantity: 500 },
  { product_id: 'prod-001', location_id: 'loc-002', current_quantity: 120 },
  // Aluminum Sheet: 35 in Main WH, 10 on Rack B
  { product_id: 'prod-002', location_id: 'loc-001', current_quantity: 35 },
  { product_id: 'prod-002', location_id: 'loc-004', current_quantity: 10 },
  // Hex Bolts: 2500 in Rack A-101, 300 on Prod Floor
  { product_id: 'prod-003', location_id: 'loc-003', current_quantity: 2500 },
  { product_id: 'prod-003', location_id: 'loc-002', current_quantity: 300 },
  // Lock Nuts: 400 in Rack A-101 (Low stock!)
  { product_id: 'prod-004', location_id: 'loc-003', current_quantity: 400 },
  // Synthetic Oil: 120 in Cold Storage (Low stock!)
  { product_id: 'prod-005', location_id: 'loc-005', current_quantity: 120 },
  // Ball Bearing: 15 in Main WH (Low stock!)
  { product_id: 'prod-006', location_id: 'loc-001', current_quantity: 15 },
  // Nitrile Gloves: 85 in Main WH
  { product_id: 'prod-007', location_id: 'loc-001', current_quantity: 85 },
  // Shipping Boxes: 450 in Main WH
  { product_id: 'prod-008', location_id: 'loc-001', current_quantity: 450 },
];

export const INITIAL_DOCUMENTS: Document[] = [
  {
    id: 'doc-001',
    code: 'REC-2026-001',
    type: 'RECEIPT',
    status: 'DONE',
    created_by: 'usr-001',
    creator_name: 'Sarah Connor',
    source_location_id: null,
    source_location_name: 'Apex Industrial Metals (Vendor)',
    destination_location_id: 'loc-001',
    destination_location_name: 'Main Warehouse',
    partner_name: 'Apex Industrial Metals',
    notes: 'Initial monthly bulk shipment',
    lines: [
      {
        id: 'line-001',
        product_id: 'prod-001',
        product_name: 'Structural Steel Rod (12mm)',
        sku: 'STL-ROD-012',
        quantity: 500,
        received_quantity: 500,
        unit_of_measure: 'kg',
      },
    ],
    created_at: '2026-02-10T10:00:00Z',
    updated_at: '2026-02-10T11:30:00Z',
  },
  {
    id: 'doc-002',
    code: 'TRF-2026-001',
    type: 'TRANSFER',
    status: 'DONE',
    created_by: 'usr-002',
    creator_name: 'John Doe',
    source_location_id: 'loc-001',
    source_location_name: 'Main Warehouse',
    destination_location_id: 'loc-002',
    destination_location_name: 'Production Floor',
    notes: 'Transfer steel for chassis assembly batch #42',
    lines: [
      {
        id: 'line-002',
        product_id: 'prod-001',
        product_name: 'Structural Steel Rod (12mm)',
        sku: 'STL-ROD-012',
        quantity: 120,
        received_quantity: 120,
        unit_of_measure: 'kg',
      },
    ],
    created_at: '2026-02-12T14:00:00Z',
    updated_at: '2026-02-12T14:45:00Z',
  },
  {
    id: 'doc-003',
    code: 'REC-2026-002',
    type: 'RECEIPT',
    status: 'READY',
    created_by: 'usr-001',
    creator_name: 'Sarah Connor',
    source_location_id: null,
    source_location_name: 'Precision Fasteners Inc (Vendor)',
    destination_location_id: 'loc-003',
    destination_location_name: 'Rack A-101',
    partner_name: 'Precision Fasteners Inc',
    notes: 'Truck arrived at dock 2, ready for unboxing and shelving',
    lines: [
      {
        id: 'line-003',
        product_id: 'prod-004',
        product_name: 'Nylon Lock Nuts M8',
        sku: 'FST-NUT-M800',
        quantity: 1000,
        received_quantity: 1000,
        unit_of_measure: 'pcs',
      },
    ],
    created_at: '2026-02-25T08:30:00Z',
    updated_at: '2026-02-25T09:10:00Z',
  },
  {
    id: 'doc-004',
    code: 'DEL-2026-001',
    type: 'DELIVERY',
    status: 'WAITING',
    created_by: 'usr-002',
    creator_name: 'John Doe',
    source_location_id: 'loc-001',
    source_location_name: 'Main Warehouse',
    destination_location_id: null,
    destination_location_name: 'Metro Machining Corp (Client)',
    partner_name: 'Metro Machining Corp',
    notes: 'Delivery Order scheduled for Friday dispatch',
    lines: [
      {
        id: 'line-004',
        product_id: 'prod-008',
        product_name: 'Corrugated Shipping Box 400x300x300',
        sku: 'PKG-BOX-403',
        quantity: 50,
        received_quantity: 0,
        unit_of_measure: 'pcs',
      },
    ],
    created_at: '2026-02-26T11:00:00Z',
    updated_at: '2026-02-26T11:00:00Z',
  },
];

export const INITIAL_LEDGER: StockLedgerEntry[] = [
  {
    id: 'ledg-001',
    document_id: 'doc-001',
    document_code: 'REC-2026-001',
    document_type: 'RECEIPT',
    product_id: 'prod-001',
    product_name: 'Structural Steel Rod (12mm)',
    sku: 'STL-ROD-012',
    source_location_id: null,
    source_location_name: 'Apex Industrial Metals',
    destination_location_id: 'loc-001',
    destination_location_name: 'Main Warehouse',
    quantity: 500,
    unit_of_measure: 'kg',
    created_by_name: 'Sarah Connor',
    timestamp: '2026-02-10T11:30:00Z',
    notes: 'Vendor delivery confirmed at dock',
  },
  {
    id: 'ledg-002',
    document_id: 'doc-002',
    document_code: 'TRF-2026-001',
    document_type: 'TRANSFER',
    product_id: 'prod-001',
    product_name: 'Structural Steel Rod (12mm)',
    sku: 'STL-ROD-012',
    source_location_id: 'loc-001',
    source_location_name: 'Main Warehouse',
    destination_location_id: 'loc-002',
    destination_location_name: 'Production Floor',
    quantity: 120,
    unit_of_measure: 'kg',
    created_by_name: 'John Doe',
    timestamp: '2026-02-12T14:45:00Z',
    notes: 'Internal movement to production rack',
  },
];
