"""create_stocksense_tables

Revision ID: da2b761c9329
Revises: 
Create Date: 2026-09-26 12:10:22.391565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da2b761c9329'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_idempotency_records_user_id'), 'idempotency_records', ['user_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('WAREHOUSE', 'RACK', 'PRODUCTION', 'VENDOR', 'CUSTOMER', 'INVENTORY_LOSS', name='location_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('low_stock_threshold', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('MANAGER', 'STAFF', name='user_role_enum'), nullable=False),
    sa.Column('otp_code', sa.String(length=10), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('RECEIPT', 'DELIVERY', 'TRANSFER', 'ADJUSTMENT', name='document_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'WAITING', 'READY', 'DONE', 'CANCELED', name='document_status_enum'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('source_location_id', sa.Uuid(), nullable=True),
    sa.Column('destination_location_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cogs', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_document_number'), 'documents', ['document_number'], unique=True)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_type'), 'documents', ['type'], unique=False)
    op.create_table('stock_levels',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('current_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'location_id')
    )
    op.create_table('document_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_lots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('initial_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_lots_created_at'), 'product_lots', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_lots_lot_number'), 'product_lots', ['lot_number'], unique=True)
    op.create_index(op.f('ix_product_lots_product_id'), 'product_lots', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_lots_remaining_quantity'), 'product_lots', ['remaining_quantity'], unique=False)
    op.create_table('stock_ledger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('source_location_id', sa.Uuid(), nullable=True),
    sa.Column('destination_location_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_ledger_document_id'), 'stock_ledger', ['document_id'], unique=False)
    op.create_index(op.f('ix_stock_ledger_entry_hash'), 'stock_ledger', ['entry_hash'], unique=False)
    op.create_index(op.f('ix_stock_ledger_product_id'), 'stock_ledger', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_ledger_timestamp'), 'stock_ledger', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_ledger_timestamp'), table_name='stock_ledger')
    op.drop_index(op.f('ix_stock_ledger_product_id'), table_name='stock_ledger')
    op.drop_index(op.f('ix_stock_ledger_entry_hash'), table_name='stock_ledger')
    op.drop_index(op.f('ix_stock_ledger_document_id'), table_name='stock_ledger')
    op.drop_table('stock_ledger')
    op.drop_index(op.f('ix_product_lots_remaining_quantity'), table_name='product_lots')
    op.drop_index(op.f('ix_product_lots_product_id'), table_name='product_lots')
    op.drop_index(op.f('ix_product_lots_lot_number'), table_name='product_lots')
    op.drop_index(op.f('ix_product_lots_created_at'), table_name='product_lots')
    op.drop_table('product_lots')
    op.drop_table('document_items')
    op.drop_table('stock_levels')
    op.drop_index(op.f('ix_documents_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_number'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_idempotency_records_user_id'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
